### ISSUE TITLE
can't resolve version?

### ISSUE THREAD

**Issue by ccmehil** [I-Valchev/rss-to-json#1]
Unable to resolve action `I-Valchev/rss-to-json@v1`, unable to find version `v1`

```
jobs:
  update-log:
    name: Update with response
    runs-on: ubuntu-latest
    steps:
      - uses: i-valchev/rss-to-json@v1
        with: 
          source: data/feeds.yaml
```

When I try to run the workflow I get the error about unable to resolve and not able to find version?
